export type CityProfile = {
  scene: string;
  weather: string;
  sound: string;
  postalMoment: string;
  memoryPrompt: string;
};

export const cityProfiles: Record<string, CityProfile> = {
  Delhi: {
    scene: "Red sandstone, crowded platforms and the blue light of an early sorting room.",
    weather: "Dry evening · warm dust",
    sound: "Porters calling beneath a station announcement",
    postalMoment: "The envelope receives its first circular date stamp and disappears into a canvas railway mail bag.",
    memoryPrompt: "Reveal the first private name, place or sentence that only the recipient will understand.",
  },
  Agra: {
    scene: "A pale morning beyond the carriage window and old rooftops passing slowly.",
    weather: "Soft haze · cool dawn",
    sound: "Steel wheels and a tea glass touching its saucer",
    postalMoment: "A clerk checks the destination code before the southbound exchange.",
    memoryPrompt: "Show the edge of an old photograph without revealing the whole picture.",
  },
  Jaipur: {
    scene: "Rose-coloured walls, desert light and a platform warmed by the afternoon.",
    weather: "Amber heat · dry wind",
    sound: "A distant whistle, bangles and a tea seller",
    postalMoment: "A violet transit mark is added beside the original Delhi stamp.",
    memoryPrompt: "Release one remembered joke or an unfinished handwritten sentence.",
  },
  Ahmedabad: {
    scene: "Long platforms, textile colours and evening light reflected in carriage glass.",
    weather: "Warm dusk · light breeze",
    sound: "Platform bells and a vendor folding paper around snacks",
    postalMoment: "The mail bag is retied with cotton cord before the western connection.",
    memoryPrompt: "Let a seven-second voice fragment play once, then settle into the memory box.",
  },
  Mumbai: {
    scene: "Rain-dark platforms, yellow station lights and a city moving without pause.",
    weather: "Monsoon rain · sea humidity",
    sound: "Local trains, rain on metal roofing and hurried footsteps",
    postalMoment: "The envelope transfers from railway mail to the Konkan coastal service.",
    memoryPrompt: "Reveal a rainy-day photograph, song title or message timestamp.",
  },
  Ratnagiri: {
    scene: "Red earth, green cuttings and the Arabian Sea appearing between tunnels.",
    weather: "Heavy rain · salt air",
    sound: "Tunnel echoes and water streaming from the roof",
    postalMoment: "A small coastal exchange mark appears while the train pauses between hills.",
    memoryPrompt: "Share a memory connected to food, travel or waiting together.",
  },
  Goa: {
    scene: "Laterite walls, palms and station signs softened by tropical rain.",
    weather: "Warm shower · bright clearing",
    sound: "Cicadas, a departing horn and rainwater beneath the platform",
    postalMoment: "The route card is checked before the overnight coastal run.",
    memoryPrompt: "Reveal a place the sender still wants to return to with the recipient.",
  },
  Karwar: {
    scene: "A quiet harbour edge, forested hills and blue-grey evening water.",
    weather: "Cloud cover · sea breeze",
    sound: "Harbour birds and a slow diesel engine",
    postalMoment: "The envelope rests briefly in a harbour mail tray before rejoining the train.",
    memoryPrompt: "Offer one calm sentence with no explanation—something meant to be felt first.",
  },
  Mangaluru: {
    scene: "Tile roofs, wet streets and palms shining after rain.",
    weather: "Coastal rain · warm night",
    sound: "Auto-rickshaws, station bells and frogs after the shower",
    postalMoment: "The northern mail seal is replaced by a Kerala-bound sorting label.",
    memoryPrompt: "Release a familiar smell, meal or family detail in a short sensory clue.",
  },
  Kozhikode: {
    scene: "A red-tiled station, halwa shops and the damp warmth of Malabar evening.",
    weather: "Light rain · humid dusk",
    sound: "Malayalam announcements and the hiss of a tea boiler",
    postalMoment: "The envelope receives its first Kerala postmark and enters the homecoming stage.",
    memoryPrompt: "Reveal a Malayalam word, nickname or phrase that makes the journey feel personal.",
  },
  Thrissur: {
    scene: "Golden evening, temple-town roads and buses crossing near the station.",
    weather: "Warm cloud · brief drizzle",
    sound: "Bus horns, distant chenda rhythm and platform chatter",
    postalMoment: "A local dispatch slip is tucked beneath the cord around the mail bundle.",
    memoryPrompt: "Show one festival, family or childhood memory as a postcard-sized fragment.",
  },
  Ernakulam: {
    scene: "City lights, ferry air and wet roads reflecting shop signs.",
    weather: "Monsoon night · harbour breeze",
    sound: "Ferry horns, traffic and rain beneath an awning",
    postalMoment: "The letter changes from express rail to the final regional network.",
    memoryPrompt: "Reveal a short voice note recorded in a quiet room or during rain.",
  },
  Kochi: {
    scene: "Harbour cranes, old ferry jetties and a blue evening over the water.",
    weather: "Salt breeze · soft rain",
    sound: "Boat engines, gulls and a distant church bell",
    postalMoment: "For overseas routes, the envelope is sealed inside an international dispatch sleeve.",
    memoryPrompt: "Share one piece of home: a kitchen sound, family phrase or photograph corner.",
  },
  Kottayam: {
    scene: "Rubber trees, rain-dark roads and a station surrounded by green.",
    weather: "Steady rain · cool air",
    sound: "Rain on leaves and a bus changing gears uphill",
    postalMoment: "The final district sorting code is written by hand on the route card.",
    memoryPrompt: "Reveal the most emotionally important clue before the arrival day.",
  },
  Alappuzha: {
    scene: "Backwater light, narrow roads and coconut palms reflected in still water.",
    weather: "Soft rain · silver morning",
    sound: "Boat engines, birds and bicycle bells",
    postalMoment: "The final postmark lands. The envelope leaves the sorting bag for the postman’s hand.",
    memoryPrompt: "Hold back the full letter; show only the recipient’s handwritten name.",
  },
  Kollam: {
    scene: "Lake air, cashew warehouses and a slower evening beside the tracks.",
    weather: "Cloudy dusk · lake breeze",
    sound: "A long horn crossing water and evening birds",
    postalMoment: "The letter is moved into the final south Kerala delivery bundle.",
    memoryPrompt: "Reveal a promise, apology or sentence the sender has carried for a long time.",
  },
  Thiruvananthapuram: {
    scene: "Red roofs, rain-washed roads and warm lamps appearing at home time.",
    weather: "Evening shower · warm breeze",
    sound: "City buses, rainwater and a gate opening",
    postalMoment: "The route closes with a destination stamp and a final walk to the door.",
    memoryPrompt: "Show the arrival card, then let the recipient physically receive the sealed letter.",
  },
  Kolkata: {
    scene: "Howrah ironwork, yellow taxis and the soft grey of a river morning.",
    weather: "Humid dawn · river haze",
    sound: "Tram bells, porters and a station clock",
    postalMoment: "The east-coast canvas bag is sealed beneath the Howrah departure board.",
    memoryPrompt: "Begin with a line that feels literary, old-fashioned or carefully remembered.",
  },
  Kharagpur: {
    scene: "A famously long platform stretching into heat and railway distance.",
    weather: "Warm noon · thin cloud",
    sound: "Multiple trains arriving and tea cups moving along the platform",
    postalMoment: "The mail bundle changes train without leaving the platform sorting trolley.",
    memoryPrompt: "Reveal a journey memory connected to missing a train, waiting or saying goodbye.",
  },
  Bhubaneswar: {
    scene: "Temple silhouettes, broad roads and a red evening sky.",
    weather: "Warm breeze · gathering cloud",
    sound: "Cycle bells and a train horn beyond the city",
    postalMoment: "An Odisha transit stamp is placed beside the eastern railway mark.",
    memoryPrompt: "Share a visual clue: colour, clothing, architecture or a small object.",
  },
  Puri: {
    scene: "Salt air, beach wind and station walls faded by sun.",
    weather: "Sea wind · bright cloud",
    sound: "Waves beyond traffic and temple bells in the distance",
    postalMoment: "The letter pauses at the coast before returning to the southbound line.",
    memoryPrompt: "Reveal a memory of faith, family travel or standing beside the sea.",
  },
  Visakhapatnam: {
    scene: "Hills meeting the sea, harbour lights and a blue coastal night.",
    weather: "Sea breeze · clear evening",
    sound: "Freight movement and waves against the harbour wall",
    postalMoment: "The mail coach is checked during a harbour-side railway exchange.",
    memoryPrompt: "Release a photograph with only one person or object kept in focus.",
  },
  Vijayawada: {
    scene: "A bright junction, river heat and trains crossing in several directions.",
    weather: "Warm night · dry air",
    sound: "Continuous announcements and metal couplings",
    postalMoment: "The envelope joins the final Coromandel connection toward Tamil Nadu.",
    memoryPrompt: "Reveal a message date or time that carries meaning for both people.",
  },
  Nellore: {
    scene: "Flat coastal fields, pale morning and station tea before sunrise.",
    weather: "Cool dawn · coastal humidity",
    sound: "Birds, a kettle and the slow rhythm of the train",
    postalMoment: "A final transit line is drawn through the previous dispatch code.",
    memoryPrompt: "Offer one gentle clue about what the final letter will say.",
  },
  Chennai: {
    scene: "Red station walls, hot air and a sea breeze reaching the city by evening.",
    weather: "Coastal heat · evening breeze",
    sound: "Suburban trains, auto horns and station clocks",
    postalMoment: "The Coromandel route closes and the envelope enters city delivery.",
    memoryPrompt: "Show the destination name and final arrival time before the seal becomes available.",
  },
  Panipat: {
    scene: "Winter fields, low mist and a small platform in pale northern light.",
    weather: "Cold morning · fog",
    sound: "A distant horn travelling through mist",
    postalMoment: "The Himalayan mail bag is checked before the climb begins.",
    memoryPrompt: "Reveal a winter memory, warm drink or shared journey detail.",
  },
  Ambala: {
    scene: "Cantonment platforms, old signs and woollen shawls in the morning cold.",
    weather: "Cool air · thin fog",
    sound: "Bootsteps, vendors and carriage doors closing",
    postalMoment: "The envelope transfers from the plains service toward the foothills.",
    memoryPrompt: "Share an object associated with departure: a ticket, scarf or handwritten list.",
  },
  Chandigarh: {
    scene: "Orderly avenues, winter sunlight and a clean modern station edge.",
    weather: "Clear afternoon · cool breeze",
    sound: "Buses, birds and a measured station announcement",
    postalMoment: "The route card receives its foothills dispatch code.",
    memoryPrompt: "Reveal a calm photograph or sentence before the journey becomes more intimate.",
  },
  Kalka: {
    scene: "A small interchange where broad-gauge distance becomes a narrow mountain railway.",
    weather: "Cool dawn · mountain cloud",
    sound: "Toy-train whistles and luggage being lifted by hand",
    postalMoment: "The envelope moves into a smaller blue canvas bag for the hill railway.",
    memoryPrompt: "Let the recipient hear a station whistle or a few seconds of mountain rain.",
  },
  Solan: {
    scene: "Pine slopes, curved platforms and houses appearing through mist.",
    weather: "Pine mist · light drizzle",
    sound: "A narrow-gauge engine and birds in the valley",
    postalMoment: "A hand stamp marks the slowest and most delicate part of the route.",
    memoryPrompt: "Reveal a quiet, vulnerable sentence rather than another visual clue.",
  },
  Shimla: {
    scene: "Cold stone, old roofs and evening lamps beneath cedar trees.",
    weather: "Mountain cold · drifting mist",
    sound: "Footsteps, bells and wind through pines",
    postalMoment: "The blue mail route ends and the envelope is carried uphill by hand.",
    memoryPrompt: "Present the sealed letter against a quiet winter arrival scene.",
  },
  Lucknow: {
    scene: "Old station arches, warm lamps and the elegance of a late-night departure.",
    weather: "Dry night · cool breeze",
    sound: "A platform clock, soft conversation and a train preparing to leave",
    postalMoment: "The central night-mail manifest is signed and placed inside the coach.",
    memoryPrompt: "Begin with a courteous old-fashioned line or family expression.",
  },
  Kanpur: {
    scene: "Industrial lights, a broad river crossing and a busy midnight junction.",
    weather: "Cool night · faint haze",
    sound: "Freight wagons and a vendor walking the platform",
    postalMoment: "The mail bag is counted during a brief midnight exchange.",
    memoryPrompt: "Reveal a timestamp, old SMS line or missed-call memory.",
  },
  Jhansi: {
    scene: "Fort-country silhouettes, dry air and a station glowing after dark.",
    weather: "Dry night · cool wind",
    sound: "A long whistle and carriage chains moving",
    postalMoment: "A central railway stamp confirms the letter’s turn toward Madhya Pradesh.",
    memoryPrompt: "Share a memory about courage, distance or leaving without saying enough.",
  },
  Bhopal: {
    scene: "Lake mist, old city roofs and blue early-morning light.",
    weather: "Cool dawn · lake haze",
    sound: "Birds over water and a station tea boiler",
    postalMoment: "The envelope pauses at the lake-city sorting room before daybreak.",
    memoryPrompt: "Reveal something reflective: a regret, gratitude or remembered kindness.",
  },
  Indore: {
    scene: "Food-stall lights, clean station signs and a lively central-India evening.",
    weather: "Mild evening · dry air",
    sound: "Vendors, scooters and a departure bell",
    postalMoment: "The night-mail cord is retied before the western connection.",
    memoryPrompt: "Share a food memory, family joke or ordinary moment that became important.",
  },
  Nashik: {
    scene: "Vineyard country, temple-town roads and a cooler western dawn.",
    weather: "Cool morning · soft cloud",
    sound: "Birds, station bells and a bus starting outside",
    postalMoment: "The envelope enters Maharashtra’s final regional dispatch.",
    memoryPrompt: "Reveal the last clue before arrival: a place name or one-line promise.",
  },
  Pune: {
    scene: "Old cantonment walls, rain-dark trees and a familiar urban morning.",
    weather: "Light rain · mild air",
    sound: "Buses, bicycles and rain beneath gulmohar trees",
    postalMoment: "The central night-mail route closes with a city delivery mark.",
    memoryPrompt: "Let the recipient receive the envelope before any final text appears.",
  },
  Dubai: {
    scene: "Airport glass, runway lights and a night suspended between countries.",
    weather: "Warm night · dry air",
    sound: "Gate announcements and rolling luggage",
    postalMoment: "The international dispatch sleeve is scanned and resealed for Europe.",
    memoryPrompt: "Reveal a small piece of home meant for someone living far away.",
  },
  "London Heathrow": {
    scene: "Grey morning light, baggage systems and the quiet order of international arrival.",
    weather: "Cool cloud · light drizzle",
    sound: "Arrival announcements and distant aircraft",
    postalMoment: "The envelope clears international sorting and receives a UK transit label.",
    memoryPrompt: "Show the distance travelled and one Malayalam or family word from home.",
  },
  London: {
    scene: "Wet pavements, terraced streets and a letterbox beneath a grey sky.",
    weather: "Fine rain · cool afternoon",
    sound: "Buses, footsteps and rain against a front window",
    postalMoment: "The overseas journey ends in the postman’s hand at the recipient’s door.",
    memoryPrompt: "Let the recipient take the letter physically, then break the seal when ready.",
  },
};

const fallback: CityProfile = {
  scene: "A railway platform, a waiting mail bag and another place quietly entering the letter’s story.",
  weather: "Changing weather · onward journey",
  sound: "A station bell and a departing train",
  postalMoment: "The envelope changes hands and receives another transit mark.",
  memoryPrompt: "Reveal one carefully chosen fragment without giving away the final letter.",
};

export function getCityProfile(city: string): CityProfile {
  return cityProfiles[city] ?? fallback;
}
